# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-24 15:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caseID', models.IntegerField(max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.IntegerField(max_length=9, unique=b'true')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='members',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.Member', to_field=b'memberID'),
        ),
    ]
