# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 21:13
from __future__ import unicode_literals

import add_member.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUploaded', models.DateTimeField(auto_now=True, null=True)),
                ('fileName', models.FileField(blank=True, null=True, upload_to='members/', validators=[add_member.validators.validate_file_ext])),
                ('fileDesc', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=30, validators=[add_member.validators.validate_rightstringlen30])),
                ('lastName', models.CharField(max_length=30, validators=[add_member.validators.validate_rightstringlen30])),
                ('jobType', models.CharField(max_length=50)),
                ('membershipStatus', models.CharField(blank=True, choices=[('RESOURCE', 'RESOURCE'), ('COMCHAIR', 'COMMITTEE CHAIR'), ('RECORDER', 'RECORDER')], max_length=30, null=True)),
                ('hireDate', models.DateField(blank=True, null=True)),
                ('memberID', models.IntegerField(blank=True, null=True, validators=[add_member.validators.validate_ninedigits])),
                ('middleName', models.CharField(blank=True, max_length=30, null=True, validators=[add_member.validators.validate_rightstringlen30])),
                ('socNum', models.IntegerField(blank=True, null=True, validators=[add_member.validators.validate_ninedigits])),
                ('city', models.CharField(blank=True, max_length=20, null=True, validators=[add_member.validators.validate_rightstringlen20])),
                ('mailAddress', models.CharField(blank=True, max_length=50, null=True, validators=[add_member.validators.validate_rightstringlen50])),
                ('mailAddress2', models.CharField(blank=True, max_length=50, null=True, validators=[add_member.validators.validate_rightstringlen50])),
                ('pCode', models.CharField(blank=True, max_length=7, null=True, validators=[add_member.validators.validate_pCode])),
                ('bDay', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDEFINED', 'Undefined')], max_length=10, null=True)),
                ('hPhone', models.CharField(blank=True, max_length=13, null=True, validators=[add_member.validators.validate_numbers])),
                ('cPhone', models.CharField(blank=True, max_length=13, null=True, validators=[add_member.validators.validate_numbers])),
                ('hEmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('campus', models.CharField(blank=True, max_length=20, null=True)),
                ('committee', models.CharField(blank=True, max_length=30, null=True, validators=[add_member.validators.validate_rightstringlen30])),
                ('memberImage', models.CharField(blank=True, max_length=30, null=True)),
                ('programChoice', models.CharField(blank=True, max_length=30, null=True, validators=[add_member.validators.validate_rightstringlen30])),
                ('posBeginDate', models.DateField(blank=True, null=True)),
                ('posEndDate', models.DateField(blank=True, null=True)),
                ('terminationDate', models.DateField(blank=True, null=True)),
                ('employeeClass', models.CharField(blank=True, max_length=4, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('jobSuffix', models.CharField(blank=True, max_length=4, null=True)),
                ('posTitle', models.CharField(blank=True, max_length=50, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('employeeStatus', models.CharField(blank=True, choices=[('A', 'ACTIVE'), ('T', 'TERMINATED')], max_length=1, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PersonFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, null=True, upload_to=b'')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='memberfiles',
            name='relatedMember',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_member.Person'),
        ),
    ]
