# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.IntegerField()),
                ('firstName', models.CharField(max_length=30)),
                ('middleName', models.CharField(max_length=30)),
                ('socNum', models.IntegerField()),
                ('city', models.CharField(max_length=20)),
                ('mailAddress', models.CharField(max_length=30)),
                ('mailAddress2', models.CharField(blank=True, max_length=30, null=True)),
                ('pCode', models.CharField(max_length=6)),
                ('bDay', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('UNDEFINED', 'Undefined')], max_length=10)),
                ('hPhone', models.CharField(blank=True, max_length=13, null=True)),
                ('cPhone', models.CharField(blank=True, max_length=13, null=True)),
                ('hEmail', models.EmailField(max_length=254)),
                ('campus', models.CharField(choices=[('SASKATOON', 'SASKATOON'), ('REGINA', 'REGINA'), ('MOOSEJAW', 'MOOSE JAW'), ('PA', 'PRINCE ALBERT')], max_length=20)),
                ('jobType', models.CharField(choices=[('FTO', 'Full-time ongoing'), ('FTED', 'Full-time end dated'), ('PTO', 'Part-time ongoing'), ('PTED', 'Part-time end dated')], max_length=30)),
                ('committee', models.CharField(max_length=30)),
                ('memberImage', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
