# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='hireDate',
            field=models.DateField(null=True),
        ),
    ]
