# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 14:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_case', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='additionalMembers',
            field=models.IntegerField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='additionalNonMembers',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='docs',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
