# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_case', '0003_remove_case_logs'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='logs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
