# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 19:41
from __future__ import unicode_literals

import add_case.validators
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_case', '0003_auto_20161107_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='department',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, validators=[add_case.validators.validate_date]),
        ),
    ]
