# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 20:08
from __future__ import unicode_literals

import add_case.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('add_case', '0004_auto_20161110_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, default='OPEN', max_length=50, validators=[add_case.validators.validate_status]),
        ),
    ]
