# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 19:55
from __future__ import unicode_literals

import add_com.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, validators=[add_com.validators.validate_com_name])),
                ('status', models.IntegerField(choices=[(1, b'Active'), (0, b'Inactive')], default='1', validators=[add_com.validators.validate_status])),
            ],
        ),
    ]
