# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-13 00:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import grievance_award_creation.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_case', '0001_initial'),
        ('add_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrievanceAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grievanceType', models.CharField(choices=[('M', 'Member'), ('P', 'Policy')], default='M', max_length=1, validators=[grievance_award_creation.validators.validate_grievance_type])),
                ('awardAmount', models.FloatField(default=500.0, validators=[grievance_award_creation.validators.validate_award_amt])),
                ('description', models.CharField(blank=True, max_length=1000, null=True, validators=[grievance_award_creation.validators.validate_description])),
                ('date', models.DateField(default=datetime.date(2017, 3, 13))),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_case.Case', validators=[grievance_award_creation.validators.validate_case])),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_member.Person', validators=[grievance_award_creation.validators.validate_recipient])),
            ],
        ),
        migrations.CreateModel(
            name='GrievanceFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_uploaded', models.DateTimeField(auto_now=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='grievance/')),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('award', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grievance_award_creation.GrievanceAward')),
            ],
        ),
    ]
