REPLACE INTO add_case_casesatellite (name) values ("PA - Academic Building");
REPLACE INTO add_case_casesatellite (name) values ("R - Parkway Building");
REPLACE INTO add_case_casesatellite (name) values ("S - Albert Ave");
REPLACE INTO add_case_casesatellite (name) values ("S - Avenue W");
REPLACE INTO add_case_casesatellite (name) values ("S - English Cres (HETT)");
REPLACE INTO add_case_casesatellite (name) values ("S - Fred Davies");
REPLACE INTO add_case_casesatellite (name) values ("S - Koyl Ave");
REPLACE INTO add_case_casesatellite (name) values ("S - Ontario Ave");
REPLACE INTO add_case_casesatellite (name) values ("S - Phoenix Building (20th St)");
REPLACE INTO add_case_casesatellite (name) values ("S - Mining Building (33rd)");
REPLACE INTO add_case_casesatellite (name) values ("S - Fourth Ave (Nursing)");
REPLACE INTO add_case_casesatellite (name) values ("S - Fourth Ave - SPAO");