# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 20:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_com', '0001_initial'),
        ('add_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liaison', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(default=datetime.date(2017, 1, 31))),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_com.Committee')),
                ('members_attending', models.ManyToManyField(to='add_member.Person')),
            ],
        ),
    ]
