# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-03 19:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import meeting.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_com', '0001_initial'),
        ('add_member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liaison', models.CharField(max_length=10)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('date', models.DateField(default=datetime.date(2017, 4, 3))),
                ('committee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='add_com.Committee')),
                ('members_attending', models.ManyToManyField(to='add_member.Person')),
            ],
        ),
        migrations.CreateModel(
            name='MeetingFiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateUploaded', models.DateTimeField(auto_now=True, null=True)),
                ('fileName', models.FileField(blank=True, null=True, upload_to='meetings/', validators=[meeting.validators.validate_file_ext])),
                ('fileDesc', models.CharField(blank=True, max_length=50, null=True)),
                ('relatedMeeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
    ]
