# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-29 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('add_member', '0001_initial'),
        ('add_case', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date(2017, 3, 29))),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
                ('contactCode', models.CharField(choices=[(b'E', b'Email'), (b'F', b'Face to face'), (b'P', b'Phone'), (b'M', b'Meeting'), (b'T', b'Text')], default='Phone', max_length=12)),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_member.Person')),
                ('relatedCase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='add_case.Case')),
            ],
        ),
        migrations.CreateModel(
            name='ContactLogFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fileName', models.FileField(blank=True, null=True, upload_to='contactlogs/')),
                ('fileDesc', models.CharField(blank=True, max_length=50, null=True)),
                ('relatedContactLog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contact_log.contactLog')),
            ],
        ),
    ]
