# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-18 18:55
from __future__ import unicode_literals

import contactLog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberID', models.IntegerField(blank=True, null=True, validators=[contactLog.validators.validate_memberID])),
                ('date', models.DateField()),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
        ),
    ]
